[project]
name = "cost"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.37.27",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
